/* EKT Smart — offline calculation core, no external services. */
(function(root){
'use strict';
const DAY=86400000, iso=d=>new Date(d).toISOString().slice(0,10), add=(d,n)=>iso(Date.parse(d)+n*DAY), diff=(a,b)=>Math.round((Date.parse(a)-Date.parse(b))/DAY), sum=a=>a.reduce((s,v)=>s+v,0), avg=a=>a.length?sum(a)/a.length:0, median=a=>{a=[...a].sort((a,b)=>a-b);return a.length?(a[Math.floor((a.length-1)/2)]+a[Math.floor(a.length/2)])/2:0;};
const key=(s,w)=>s+'|'+w;
function demo(){
 let seed=2417; const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
 const date='2026-09-23', names=['Кабель ВВГнг 3×2,5','Кабель ВВГнг 3×1,5','Кабель силовой 5×4','Провод ПВС 2×0,75','Гофра ПВХ 20 мм','Кабель-канал 40×25','Розетка с заземлением','Выключатель одноклавишный','Рамка двухместная','Розетка накладная','Автомат 16 А','Автомат 25 А','УЗО 40 А','Диффавтомат 16 А','Контактор 25 А','Щит 12 модулей','Щит 24 модуля','DIN-рейка 35 мм','Шина нулевая','Клемма 2,5 мм²','Лампа LED 10 Вт','Светильник линейный','Прожектор 50 Вт','Датчик движения','Лента LED 12 В','Изолента ПВХ','Стяжка 200 мм','Наконечник НШВИ','Коробка распаечная','Реле напряжения'];
 const db={version:1,demo:true,date,products:[],suppliers:[{supplier_id:'S1',supplier_name:'Кабель Снаб',lead_time_days:10},{supplier_id:'S2',supplier_name:'Электро Партнёр',lead_time_days:7},{supplier_id:'S3',supplier_name:'Свет Комплект',lead_time_days:14}],warehouses:[{warehouse_id:'W1',warehouse_name:'Алматы · основной'},{warehouse_id:'W2',warehouse_name:'Астана · региональный'}],sales:[],inventory:[],inbound:[],stockouts:[],category_settings:[],decisions:{},orders:[]};
 const cats=['Кабель и провод','Электроустановка','Защита и управление','Щитовое оборудование','Освещение','Монтаж'];
 cats.forEach(category=>db.category_settings.push({category,additional_growth_pct:0,review_period_days:7,safety_stock_days:5}));
 names.forEach((name,i)=>{const sku='EKT-'+String(i+1).padStart(3,'0'),p={sku,name,category:cats[Math.floor(i/5)],unit:i<6||i===24?'м':'шт.',supplier_id:'S'+(i<6?1:i<20?2:3),purchase_price:Math.round(150+rnd()*9500),pack_size:i<6?10:1,min_order_qty:i<6?20:1}; db.products.push(p);
 db.warehouses.forEach((w,wi)=>{const base=(3+i%7)*(wi?0.6:1),start=i===29?add(date,-45):add(date,-730),st=i%6===2?{sku,warehouse_id:w.warehouse_id,start_date:add(date,-38),end_date:add(date,-24)}:null;if(st)db.stockouts.push(st);
 for(let d=start;d<date;d=add(d,1)){if(st&&d>=st.start_date&&d<=st.end_date)continue;const age=diff(d,add(date,-730)),season=i%6===0?1+0.7*Math.sin((new Date(d).getUTCMonth()-3)/12*Math.PI*2):1,trend=i%6===1?0.55+age/730:1,week=new Date(d).getUTCDay()===0?0.5:1;let q=Math.max(0,Math.round(base*season*trend*week*(0.6+rnd()*0.8)));if(i%6===4)q=rnd()<0.12?Math.round(base*2):0;if(q)db.sales.push({sale_id:sku+'-'+wi+'-'+d,date:d,sku,warehouse_id:w.warehouse_id,customer_id:'C-'+String(1+Math.floor(rnd()*24)).padStart(3,'0'),quantity:q,selling_price:Math.round(p.purchase_price*1.3)});
 if(i===5&&new Date(d).getUTCDate()===12)db.sales.push({sale_id:'repeat-'+wi+'-'+d,date:d,sku,warehouse_id:w.warehouse_id,customer_id:'C-080',quantity:200,selling_price:p.purchase_price*1.25});}
 if(i===0||i===10)db.sales.push({sale_id:'project-'+i+'-'+wi,date:add(date,-17),sku,warehouse_id:w.warehouse_id,customer_id:'C-099',quantity:5000,selling_price:p.purchase_price*1.2});
 db.inventory.push({as_of_date:date,sku,warehouse_id:w.warehouse_id,on_hand:Math.round(base*([4,10,5,70,20,7][i%6]))});
 if(i%3===0)db.inbound.push({inbound_id:'IN-'+i+'-'+wi,sku,warehouse_id:w.warehouse_id,supplier_id:p.supplier_id,quantity:Math.round(base*8),expected_date:add(date,6+i%5),status:'confirmed'});
 });});return db;
}
function prepare(db){
 const by=new Map(), groups=new Map();for(const s of db.sales){if(s.date>=db.date)continue;const k=key(s.sku,s.warehouse_id);if(!by.has(k))by.set(k,[]);by.get(k).push(s);const g=k+'|'+s.customer_id+'|'+s.date;if(!groups.has(g))groups.set(g,{id:g,sku:s.sku,warehouse_id:s.warehouse_id,customer_id:s.customer_id,date:s.date,quantity:0,sale_ids:[]});const x=groups.get(g);x.quantity+=+s.quantity;x.sale_ids.push(s.sale_id);}
 const grouped=new Map();for(const g of groups.values()){const k=key(g.sku,g.warehouse_id);if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(g);}
 const anomalies=[],excluded=new Set();for(const [k,gs] of grouped){const vals=gs.map(g=>g.quantity),m=median(vals),mad=median(vals.map(v=>Math.abs(v-m))),threshold=Math.max(m*5,m+8*Math.max(1,mad),20),big=gs.filter(g=>g.quantity>threshold);for(const g of gs){const recurrence=big.filter(x=>x.customer_id===g.customer_id).length,automatic=g.quantity>threshold&&recurrence<3,decision=db.decisions?.[g.id]||'auto';if(g.quantity>threshold||decision!=='auto'){const remove=decision==='oneoff'||(decision==='auto'&&automatic);if(remove)g.sale_ids.forEach(id=>excluded.add(id));anomalies.push({...g,median:m,threshold,recurrence,automatic,decision,excluded:remove,confidence:gs.length>=30?'Достаточно истории':'Мало истории'});}}}
 return {by,excluded,anomalies};
}
function model(db,p,w,prep){
 const records=prep.by.get(key(p.sku,w))||[], stockouts=db.stockouts.filter(s=>s.sku===p.sku&&s.warehouse_id===w),start=records.length?records.reduce((m,r)=>r.date<m?r.date:m,db.date):add(db.date,-1),days=Math.min(730,Math.max(1,diff(db.date,start))),series=[],actual=new Map(),clean=new Map();
 records.forEach(r=>{actual.set(r.date,(actual.get(r.date)||0)+ +r.quantity);if(!prep.excluded.has(r.sale_id))clean.set(r.date,(clean.get(r.date)||0)+ +r.quantity);});
 for(let i=days;i>0;i--){const d=add(db.date,-i);series.push({date:d,actual:actual.get(d)||0,regular:clean.get(d)||0,stockout:stockouts.some(s=>d>=s.start_date&&d<=s.end_date),imputed:0});}
 const available=series.filter(r=>!r.stockout),recent=available.slice(-90),fallback=avg(recent.map(r=>r.regular));for(const r of series){if(r.stockout){let peers=available.filter(x=>Math.abs(diff(x.date,r.date))<=56&&new Date(x.date).getUTCDay()===new Date(r.date).getUTCDay());if(!peers.length)peers=recent;r.imputed=avg(peers.map(x=>x.regular));r.regular=r.imputed;}}
 const seasonal=days>=650,month=Array(12).fill(1);if(seasonal){const overall=avg(series.map(r=>r.regular)),pairs=series.slice(365).map((r,i)=>(r.regular-series[i].regular)/365),annualSlope=avg(pairs),mid=(series.length-1)/2;const normalized=series.map((r,i)=>({date:r.date,value:r.regular/Math.max(overall*.2,overall+annualSlope*(i-mid),.001)}));for(let m=0;m<12;m++)month[m]=overall?Math.max(.25,Math.min(4,avg(normalized.filter(r=>new Date(r.date).getUTCMonth()===m).map(r=>r.value)))):1;}
 const ds=series.map(r=>r.regular/month[new Date(r.date).getUTCMonth()]),level=avg(ds.slice(-56)),trendSeries=ds.slice(-180),center=(trendSeries.length-1)/2,mean=avg(trendSeries),numerator=sum(trendSeries.map((v,i)=>(i-center)*(v-mean))),denominator=sum(trendSeries.map((v,i)=>(i-center)**2)),slope=days>=112&&level>0&&denominator>0?Math.max(-.005,Math.min(.005,numerator/denominator/level)):0;
 const cfg=db.category_settings.find(c=>c.category===p.category)||{additional_growth_pct:0,review_period_days:7,safety_stock_days:5};
 const predict=n=>Math.max(0,level*(1+slope*Math.min(n,90))*month[new Date(add(db.date,n)).getUTCMonth()]*(1+(+cfg.additional_growth_pct||0)/100));
 return {series,predict,cfg,seasonal,slope,level,restored:sum(series.map(r=>r.imputed)),excluded:sum(records.filter(r=>prep.excluded.has(r.sale_id)).map(r=>+r.quantity)),confidence:days<90?'Мало истории':days<650?'Без годовой сезонности':'24 месяца истории',days,fallback};
}
function simulate(db,p,w,m,{delay=0,growth=0,order=0,horizon=60}={}){const supplier=db.suppliers.find(s=>s.supplier_id===p.supplier_id),lead=+supplier.lead_time_days,inv=db.inventory.find(i=>i.sku===p.sku&&i.warehouse_id===w),incoming=db.inbound.filter(i=>i.sku===p.sku&&i.warehouse_id===w&&i.status==='confirmed'&&i.expected_date>=db.date);let stock=+(inv?.on_hand||0),lost=0;const path=[];for(let n=0;n<=horizon;n++){const date=add(db.date,n),received=sum(incoming.filter(i=>diff(i.expected_date,db.date)+delay===n).map(i=>+i.quantity))+(n===lead+delay?order:0);stock+=received;const demand=m.predict(n)*(1+growth/100),missing=Math.max(0,demand-stock);stock=Math.max(0,stock-demand);lost+=missing;path.push({date,n,stock,demand,missing,lost,received});}return path;}
function calculate(db){const prep=prepare(db),rows=[];for(const inv of db.inventory){const p=db.products.find(p=>p.sku===inv.sku);if(!p)continue;const supplier=db.suppliers.find(s=>s.supplier_id===p.supplier_id);if(!supplier)continue;const m=model(db,p,inv.warehouse_id,prep),lead=+supplier.lead_time_days,horizon=lead+ +m.cfg.review_period_days,demand=sum(Array.from({length:horizon},(_,i)=>m.predict(i))),safety=sum(Array.from({length:+m.cfg.safety_stock_days},(_,i)=>m.predict(horizon+i))),incoming=db.inbound.filter(i=>i.sku===p.sku&&i.warehouse_id===inv.warehouse_id&&i.status==='confirmed'),timely=sum(incoming.filter(i=>i.expected_date>=db.date&&diff(i.expected_date,db.date)<horizon).map(i=>+i.quantity)),raw=Math.max(0,demand+safety- +inv.on_hand-timely),qty=raw?Math.ceil(Math.max(raw,+p.min_order_qty||0)/(+p.pack_size||1))*(+p.pack_size||1):0,path=simulate(db,p,inv.warehouse_id,m),first=path.find(r=>r.missing>.001),risk=first?.n??null,urgency=risk!==null&&risk<=lead?'Высокая':risk!==null&&risk<horizon?'Средняя':'Плановая',perDay=avg(path.slice(0,14).map(r=>r.demand));rows.push({...p,warehouse_id:inv.warehouse_id,supplier_name:supplier.supplier_name,on_hand:+inv.on_hand,inbound:sum(incoming.map(i=>+i.quantity)),timely,demand,safety,raw,qty,horizon,lead,cover:perDay?+inv.on_hand/perDay:null,risk,urgency,excess:+inv.on_hand>sum(path.map(r=>r.demand)),amount:p.purchase_price===''||p.purchase_price==null?null:qty* +p.purchase_price,model:m,path,overdue:incoming.filter(i=>i.expected_date<db.date).length});}return {rows,anomalies:prep.anomalies};}
const api={demo,prepare,model,calculate,simulate,add,diff,sum,avg,key};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.EKT=api;
})(typeof globalThis!=='undefined'?globalThis:this);
