/* Minimal OOXML workbook reader/writer. No macros or network access. */
const Files=(()=>{
const enc=new TextEncoder(),dec=new TextDecoder(),xml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc(a){let c=0xffffffff;for(const b of a)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function zip(entries){let off=0;const chunks=[],central=[];for(const [name,str] of Object.entries(entries)){const n=enc.encode(name),b=enc.encode(str),c=crc(b),h=new Uint8Array(30+n.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,c,true);v.setUint32(18,b.length,true);v.setUint32(22,b.length,true);v.setUint16(26,n.length,true);h.set(n,30);chunks.push(h,b);const z=new Uint8Array(46+n.length),w=new DataView(z.buffer);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint32(16,c,true);w.setUint32(20,b.length,true);w.setUint32(24,b.length,true);w.setUint16(28,n.length,true);w.setUint32(42,off,true);z.set(n,46);central.push(z);off+=h.length+b.length;}const end=new Uint8Array(22),e=new DataView(end.buffer),size=central.reduce((s,a)=>s+a.length,0);e.setUint32(0,0x06054b50,true);e.setUint16(8,central.length,true);e.setUint16(10,central.length,true);e.setUint32(12,size,true);e.setUint32(16,off,true);return new Blob([...chunks,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});}
const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
function workbook(sheets){const names=Object.keys(sheets),entries={'_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'};entries['[Content_Types].xml']='<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'+names.map((n,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')+'</Types>';entries['xl/workbook.xml']='<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+names.map((n,i)=>`<sheet name="${xml(n)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')+'</sheets></workbook>';entries['xl/_rels/workbook.xml.rels']='<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+names.map((n,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')+'</Relationships>';names.forEach((n,i)=>{const s=sheets[n],rows=Array.isArray(s[0])?s:[Object.keys(s[0]||{}),...s.map(r=>Object.keys(s[0]||{}).map(k=>r[k]))];entries[`xl/worksheets/sheet${i+1}.xml`]='<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map((r,ri)=>`<row r="${ri+1}">`+r.map((v,ci)=>typeof v==='number'&&Number.isFinite(v)?`<c r="${col(ci)}${ri+1}"><v>${v}</v></c>`:`<c r="${col(ci)}${ri+1}" t="inlineStr"><is><t xml:space="preserve">${xml(v)}</t></is></c>`).join('')+'</row>').join('')+'</sheetData></worksheet>';});return zip(entries);}
async function unzip(buffer){const a=new Uint8Array(buffer),v=new DataView(buffer);let e=a.length-22;while(e>=Math.max(0,a.length-65557)&&v.getUint32(e,true)!==0x06054b50)e--;if(e<0)throw Error('Файл не является XLSX. Формат XLS не поддерживается.');const count=v.getUint16(e+10,true);let pos=v.getUint32(e+16,true),total=0;const out={};for(let i=0;i<count;i++){if(v.getUint32(pos,true)!==0x02014b50)throw Error('Повреждён архив XLSX');const method=v.getUint16(pos+10,true),size=v.getUint32(pos+20,true),expanded=v.getUint32(pos+24,true),nl=v.getUint16(pos+28,true),extra=v.getUint16(pos+30,true),comment=v.getUint16(pos+32,true),off=v.getUint32(pos+42,true),name=dec.decode(a.slice(pos+46,pos+46+nl));total+=expanded;if(total>100*1024*1024)throw Error('Распакованный файл превышает 100 МБ');const start=off+30+v.getUint16(off+26,true)+v.getUint16(off+28,true);let bytes=a.slice(start,start+size);if(method===8){const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));bytes=new Uint8Array(await new Response(stream).arrayBuffer());}else if(method!==0)throw Error('Неподдерживаемое сжатие XLSX');if(name.endsWith('.xml')||name.endsWith('.rels'))out[name]=dec.decode(bytes);pos+=46+nl+extra+comment;}return out;}
const parseXml=s=>{const d=new DOMParser().parseFromString(s,'application/xml');if(d.getElementsByTagName('parsererror').length)throw Error('Ошибка структуры XML');return d;},els=(d,n)=>Array.from(d.getElementsByTagNameNS('*',n));
function objects(rows){if(!rows.length)return [];const headers=rows[0].map(v=>String(v??'').trim());return rows.slice(1).filter(r=>r.some(v=>v!==''&&v!=null)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
async function readXlsx(buffer){const z=await unzip(buffer),book=parseXml(z['xl/workbook.xml']||''),rels=els(parseXml(z['xl/_rels/workbook.xml.rels']||''),'Relationship'),shared=z['xl/sharedStrings.xml']?els(parseXml(z['xl/sharedStrings.xml']),'si').map(x=>els(x,'t').map(t=>t.textContent).join('')):[],out={};for(const sh of els(book,'sheet')){const id=sh.getAttribute('r:id'),rel=rels.find(r=>r.getAttribute('Id')===id);if(!rel)continue;let target=rel.getAttribute('Target');target=target.startsWith('/')?target.slice(1):'xl/'+target;target=target.replace(/\/\.\//g,'/');const sheet=z[target];if(!sheet)continue;const rows=els(parseXml(sheet),'row').map(r=>{const a=[];for(const c of els(r,'c')){const ref=c.getAttribute('r')||'',letters=ref.replace(/[0-9]/g,''),idx=[...letters].reduce((s,x)=>s*26+x.charCodeAt(0)-64,0)-1,t=c.getAttribute('t'),value=els(c,'v')[0]?.textContent||'';a[idx]=t==='inlineStr'?els(c,'t').map(x=>x.textContent).join(''):t==='s'?shared[+value]||'':value;}return a;});out[sh.getAttribute('name')]=objects(rows);}return out;}
function csvRows(text){text=text.replace(/^\uFEFF/,'');const first=text.split(/\r?\n/)[0],sep=first.includes(';')?';':',',rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===sep&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('Незакрытая кавычка в CSV');if(cell||row.length){row.push(cell);rows.push(row);}return objects(rows);}
function csv(rows){const headers=Object.keys(rows[0]||{}),safe=v=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s)&&typeof v!=='number')s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};return new Blob(['\uFEFF'+[headers,...rows.map(r=>headers.map(k=>r[k]))].map(r=>r.map(safe).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000);}
return {workbook,readXlsx,csvRows,csv,download};})();
